# Generated by Django 4.0.6 on 2022-07-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('obj', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2048)),
            ],
        ),
    ]
