# Generated by Django 4.0.6 on 2022-07-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('obj', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2048)),
            ],
        ),
    ]
