# Generated by Django 4.0.6 on 2022-07-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_messagereceived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='to',
        ),
    ]
