# Generated by Django 4.0.6 on 2022-07-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_adminmessage_adminmessagereceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessagereceived',
            name='session',
            field=models.CharField(default='a5933d5be5da16934cf34eb38485daf44956d1dd01b0989ea1d2286cea7c64ac', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.CharField(default='a5933d5be5da16934cf34eb38485daf44956d1dd01b0989ea1d2286cea7c64ac', max_length=64),
            preserve_default=False,
        ),
    ]
