# Generated by Django 4.0.6 on 2022-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_adminmessagereceived_session_message_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessagereceived',
            name='session',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
