# Generated by Django 4.0.6 on 2022-07-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_alter_adminmessagereceived_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adminmessagereceived',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messagereceived',
            name='content',
            field=models.TextField(),
        ),
    ]
